### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by aoudiamoncef** [mongoose-os-apps/mq135#1]
Hello @cpq,

I haven't change my source code, with the new updates of of MOS, i get this error :+1: 

   Adding api_http.js: 3770

     Adding sys_ro_vars_schema.json: 332
     Adding api_gpio.js: 2731
     Adding api_adc.js: 286
     Adding sys_config_schema.json: 3911
     Image stats: size=262144, space: total=233681, used=69778, free=163903
  GEN   /fwbuild-volumes/latest/apps/MQ135_MONGOOSE_OS/esp8266/build_contexts/build_ctx_161346937/build/gen/build_info.c
  GEN   /fwbuild-volumes/latest/apps/MQ135_MONGOOSE_OS/esp8266/build_contexts/build_ctx_161346937/build/gen/mg_build_info.c
  AR    /app/build/objs/mongoose-os.a
  CC    /fwbuild-volumes/latest/apps/MQ135_MONGOOSE_OS/esp8266/build_contexts/build_ctx_161346937/build/gen/build_info.c -> /app/build/objs/build_info.c.o
  CC    /fwbuild-volumes/latest/apps/MQ135_MONGOOSE_OS/esp8266/build_contexts/build_ctx_161346937/build/gen/mg_build_info.c -> /app/build/objs/mg_build_info.c.o
  LD    /app/build/objs/MQ135_MONGOOSE_OS.elf
/app/build/objs/deps_init.c.o:(.rodata.descrs+0x14): undefined reference to `mgos_mq135_init'
collect2: error: ld returned 1 exit status
/mongoose-os/fw/platforms/esp8266/Makefile.build:427: recipe for target '/app/build/objs/MQ135_MONGOOSE_OS.elf' failed
make: *** [/app/build/objs/MQ135_MONGOOSE_OS.elf] Error 1
make: Leaving directory '/app'
Error: exit status 2
Error: build failed

It worked before updating MOS.

Thank you

**Comment by aoudiamoncef** [comment]
hello @cpq , i'm wainting for reply about this issue please.

**Comment by dimonomid** [comment]
@Sparow199 , it's not entirely clear which mos version you had before and which you have now, but the error says there is no initialization function for mq135 lib (not app), and I believe that the requirement for each lib to have init functions was there from the very beginning of libs implementation.

The last commit https://github.com/mongoose-os-apps/mq135/commit/980f4669adb5d12de8530e8a4e66c14126dff053 adds the mq135 lib to your app:

```yaml
 - origin: https://github.com/mongoose-os-libs/mq135
```

And if we look at that lib ( https://github.com/mongoose-os-libs/mq135 ), there's no C source code at all, so yeah, there's no init function. Let's fix it.

Library's [mos.yml](https://github.com/mongoose-os-libs/mq135/blob/master/mos.yml) already references source directory `src`:
```yaml
sources:
  - src
```
That directory does not exist yet though, so let's create one, and put some C file in it, say, `mq135.c`:
```
└── src
    └── mq135.c
```
With the following contents:
```c
#include <stdbool.h>

bool mgos_mq135_init(void) {
  return true;
}
```
Commit that change, do a clean build for your app:
```
mos build --arch esp8266 --clean
```
And it will work now.

**Comment by aoudiamoncef** [comment]
@dimonomid , thank you for fixing issue.
i did it and all seem to be ok with  example, but i can't find it in MOS IDE yet.

Thank you.
